export interface AgentTaskDefectSummary {
	scope?: string | null;
	total_count?: number | null;
	severity_counts?: {
		critical?: number | null;
		high?: number | null;
		medium?: number | null;
		low?: number | null;
		info?: number | null;
	} | null;
	status_counts?: {
		pending?: number | null;
		verified?: number | null;
		false_positive?: number | null;
		[key: string]: number | null | undefined;
	} | null;
}

export interface AgentTask {
	id: string;
	project_id: string;
	name: string;
	description?: string | null;
	task_type?: string | null;
	status: string;
	current_phase?: string | null;
	current_step?: string | null;
	total_files?: number | null;
	indexed_files?: number | null;
	analyzed_files?: number | null;
	files_with_findings?: number | null;
	total_chunks?: number | null;
	findings_count?: number | null;
	verified_count?: number | null;
	false_positive_count?: number | null;
	total_iterations?: number | null;
	tool_calls_count?: number | null;
	tokens_used?: number | null;
	critical_count?: number | null;
	high_count?: number | null;
	medium_count?: number | null;
	low_count?: number | null;
	verified_critical_count?: number | null;
	verified_high_count?: number | null;
	verified_medium_count?: number | null;
	verified_low_count?: number | null;
	defect_summary?: AgentTaskDefectSummary | null;
	quality_score?: number | null;
	security_score?: number | null;
	created_at: string;
	started_at?: string | null;
	completed_at?: string | null;
	updated_at?: string | null;
	progress_percentage?: number | null;
	audit_scope?: Record<string, unknown> | null;
	target_vulnerabilities?: string[] | null;
	verification_level?: string | null;
	tool_evidence_protocol?: string | null;
	exclude_patterns?: string[] | null;
	target_files?: string[] | null;
	error_message?: string | null;
	[key: string]: unknown;
}

export interface AgentFinding {
	id: string;
	task_id: string;
	vulnerability_type?: string | null;
	severity?: string | null;
	title?: string | null;
	display_title?: string | null;
	description?: string | null;
	description_markdown?: string | null;
	file_path?: string | null;
	line_start?: number | null;
	line_end?: number | null;
	resolved_file_path?: string | null;
	resolved_line_start?: number | null;
	code_snippet?: string | null;
	code_context?: string | null;
	cwe_id?: string | null;
	cwe_name?: string | null;
	context_start_line?: number | null;
	context_end_line?: number | null;
	status?: string | null;
	is_verified?: boolean | null;
	verdict?: string | null;
	reachability?: string | null;
	authenticity?: string | null;
	verification_evidence?: string | null;
	verification_todo_id?: string | null;
	verification_fingerprint?: string | null;
	reachability_file?: string | null;
	reachability_function?: string | null;
	reachability_function_start_line?: number | null;
	reachability_function_end_line?: number | null;
	flow_path_score?: number | null;
	flow_call_chain?: string[] | null;
	function_trigger_flow?: string[] | null;
	flow_control_conditions?: string | null;
	logic_authz_evidence?: string | null;
	has_poc?: boolean | null;
	poc_code?: string | null;
	trigger_flow?: string | null;
	poc_trigger_chain?: string[] | null;
	suggestion?: string | null;
	fix_code?: string | null;
	report?: string | null;
	ai_explanation?: string | null;
	ai_confidence?: number | null;
	confidence?: number | null;
	source_node_id?: string | null;
	source_node_name?: string | null;
	created_at?: string | null;
	[key: string]: unknown;
}
