rules:
- id: rules_lgpl_javascript_electronjs_rule-electron-disable-websecurity
  patterns:
  - pattern-either:
    - pattern: |
        new BrowserWindow({webPreferences: {webSecurity: false}})
    - pattern: |
        var $X = {webPreferences: {webSecurity: false}};
  message: |
    Disabling webSecurity will disable the same-origin policy and allows the execution of insecure code from any domain.
  languages:
  - javascript
  severity: ERROR
  metadata:
    owasp:
    - A6:2017-Security Misconfiguration
    - A05:2021-Security Misconfiguration
    cwe: CWE-346
    shortDescription: Origin validation error
    security-severity: CRITICAL
    category: security
