rules:
- id: rules_lgpl_javascript_electronjs_rule-electron-disable-websecurity
  patterns:
  - pattern-either:
    - pattern: |
        new BrowserWindow({webPreferences: {webSecurity: false}})
    - pattern: |
        var $X = {webPreferences: {webSecurity: false}};
  message: |
    检测到客户端容器安全配置风险（规则：rules_lgpl_javascript_electronjs_rule-electron-disable-websecurity）。危害：WebView/Electron
    安全配置过宽可能允许调试、明文加载或跨域访问，扩大代码执行和数据窃取风险。建议：关闭危险调试/禁用项，只加载可信 HTTPS 内容并隔离不可信页面。
  languages:
  - javascript
  severity: ERROR
  metadata:
    owasp:
    - A6:2017-Security Misconfiguration
    - A05:2021-Security Misconfiguration
    cwe: CWE-346
    shortDescription: Origin validation error
    security-severity: CRITICAL
    category: security
