"""empty message

Revision ID: 311959fcb446
Revises: 6b036f40425a
Create Date: 2026-01-30 14:58:07.016056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311959fcb446'
down_revision = '6b036f40425a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###






